### ISSUE TITLE
Error in annotation transfer subcommand

### ISSUE THREAD

**Issue by elhossary** [Sung-Huan/ANNOgesic#13]
Traceback (most recent call last):
  File "/usr/local/bin/annogesic", line 2227, in <module>
    main()
  File "/usr/local/bin/annogesic", line 2143, in main                                                                                                                           args.func(controller)                                                                                                                                                     File "/usr/local/bin/annogesic", line 2159, in run_RATT                                                                                                                       controller.ratt()                                                                                                                                                         File "/usr/local/lib/python3.6/dist-packages/annogesiclib/controller.py", line 277, in ratt                                                                                   ratt.annotation_transfer(args_ratt, log)                                                                                                                                  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/ratt.py", line 197, in annotation_transfer                                                                          out_gbk = self._convert_embl(args_ratt.ref_gbki, log)
AttributeError: 'ArgsContainer' object has no attribute 'ref_gbki'

**Comment by Sung-Huan** [comment]
Sorry for such stupid bug. I will fix it soon.

**Comment by Sung-Huan** [comment]
Done. Please update the version.

**Comment by elhossary** [comment]
Thank you for your kind support, I will check it
