### ISSUE TITLE
Error in sRNA_target prediction

### ISSUE THREAD

**Issue by elhossary** [Sung-Huan/ANNOgesic#14]
See traceback
Ranking for IntaRNA
Traceback (most recent call last):
  File "/usr/local/bin/annogesic", line 2230, in <module>
    main()
  File "/usr/local/bin/annogesic", line 2146, in main
    args.func(controller)
  File "/usr/local/bin/annogesic", line 2207, in sRNA_target
    controller.srna_target()
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/controller.py", line 831, in srna_target
    srnatarget.run_srna_target_prediction(args_tar, log)
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/srna_target.py", line 599, in run_srna_target_prediction
    self._merge_rnaplex_rnaup(prefixs, args_tar, log)
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/srna_target.py", line 462, in _merge_rnaplex_rnaup
    os.path.join(self.gff_path, prefix + ".gff"))
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/merge_rnaplex_rnaup.py", line 674, in merge_srna_target
    length)
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/merge_rnaplex_rnaup.py", line 108, in print_rank_one
    length)
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/merge_rnaplex_rnaup.py", line 50, in mod_srna_tar_pos
    start = int(pos.split(",")[0])
ValueError: invalid literal for int() with base 10: 'NZ_CP024992.1_srna322'

**Comment by Sung-Huan** [comment]
The error is from IntaRNA which will also generates some results which missing some required information. I already add come code for checking the results of IntaRNA. Please update the version.
