### ISSUE TITLE
Transcript detection error

### ISSUE THREAD

**Issue by gjh34** [Sung-Huan/ANNOgesic#22]
Hi,

I am trying to predict sRNAs from RNA-seq data using ANNOgesic 1.0.16, and I should perform transcript detection first accroding to the tutorial. However, I got errors when performed transcript detection. The command I used is as follows:
```
annogesic transcript --project_path /public/guanjiahao/rna_seq/ANNOgesic --frag_libs /public/guanjiahao/rna_seq/ANNOgesic/input/wigs/fragment/WT_1.Forward.wig:frag:1:a:+ \
/public/guanjiahao/rna_seq/ANNOgesic/input/wigs/fragment/WT_1.Reverse.wig:frag:1:a:- \
/public/guanjiahao/rna_seq/ANNOgesic/input/wigs/fragment/WT_2.Forward.wig:frag:1:b:+ \
/public/guanjiahao/rna_seq/ANNOgesic/input/wigs/fragment/WT_2.Reverse.wig:frag:1:b:- \
/public/guanjiahao/rna_seq/ANNOgesic/input/wigs/fragment/WT_3.Forward.wig:frag:1:c:+ \
/public/guanjiahao/rna_seq/ANNOgesic/input/wigs/fragment/WT_3.Reverse.wig:frag:1:c:- --replicate_frag all_2
```

And I got these following error messages:
```
Running transcript detection
Parsing WT_1.Forward.wig
Parsing WT_1.Reverse.wig
Parsing WT_2.Forward.wig
Parsing WT_2.Reverse.wig
Parsing WT_3.Forward.wig
Parsing WT_3.Reverse.wig
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_1.Forward_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_1.Reverse_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_2.Forward_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_2.Reverse_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_3.Forward_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_3.Reverse_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_1.Forward_STRAIN_NC_016838.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_1.Reverse_STRAIN_NC_016838.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_2.Forward_STRAIN_NC_016838.1: No such file or directory
sh: line 1: .wig: command not found
......
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_1.Forward_STRAIN_NC_016841.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_1.Reverse_STRAIN_NC_016841.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_2.Forward_STRAIN_NC_016841.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_2.Reverse_STRAIN_NC_016841.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_3.Forward_STRAIN_NC_016841.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_3.Reverse_STRAIN_NC_016841.1: No such file or directory
sh: line 1: .wig: command not found
Importing fragment wig files
Computing transcripts for NC_016839.1

Computing transcripts for NC_016840.1

Computing transcripts for NC_016847.1

Computing transcripts for NC_016841.1

Computing transcripts for NC_016845.1

Computing transcripts for NC_016838.1

Computing transcripts for NC_016846.1

/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016839.1
_fragment
/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016840.1
_fragment
/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016847.1
_fragment
/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016841.1
_fragment
/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016845.1
_fragment
/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016838.1
_fragment
/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016846.1
_fragment
Traceback (most recent call last):
  File "/public/guanjiahao/biosoft/ANNOgesic/bin/annogesic", line 2230, in <module>
    main()
  File "/public/guanjiahao/biosoft/ANNOgesic/bin/annogesic", line 2146, in main
    args.func(controller)
  File "/public/guanjiahao/biosoft/ANNOgesic/bin/annogesic", line 2183, in run_Transcript_Assembly
    controller.transcript()
  File "/public/guanjiahao/biosoft/ANNOgesic/bin/annogesiclib/controller.py", line 463, in transcript
    transcript.run_transcript(args_tran, log)
  File "/public/guanjiahao/biosoft/ANNOgesic/bin/annogesiclib/transcript.py", line 320, in run_transcript
    args_tran.gffs, "tmp"), None, None)
  File "/home/guanjiahao/miniconda3/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

It seemed that there were something wrong within the tmp directory, so I checked the ANNOgesic directory:
```
$ tree ANNOgesic
ANNOgesic
├── input
│   ├── BAMs
│   │   ├── BAMs_map_reference_genomes
│   │   │   ├── fragment
│   │   │   └── tex_notex
│   │   └── BAMs_map_related_genomes
│   │       ├── fragment
│   │       └── tex_notex
│   ├── databases
│   ├── manual_processing_sites
│   ├── manual_TSSs
│   ├── mutation_tables
│   ├── reads
│   ├── references
│   │   ├── annotations
│   │   └── fasta_files
│   ├── riboswitch_ID_file
│   ├── RNA_thermometer_ID_file
│   └── wigs
│       ├── fragment
│       │   ├── WT_1.Forward.wig
│       │   ├── WT_1.Reverse.wig
│       │   ├── WT_2.Forward.wig
│       │   ├── WT_2.Reverse.wig
│       │   ├── WT_3.Forward.wig
│       │   └── WT_3.Reverse.wig
│       └── tex_notex
├── output
│   └── transcripts
│       ├── gffs
│       │   ├── NC_016838.1\012_transcript.gff
│       │   ├── NC_016839.1\012_transcript.gff
│       │   ├── NC_016840.1\012_transcript.gff
│       │   ├── NC_016841.1\012_transcript.gff
│       │   ├── NC_016845.1\012_transcript.gff
│       │   ├── NC_016846.1\012_transcript.gff
│       │   └── NC_016847.1\012_transcript.gff
│       ├── log.txt
│       ├── statistics
│       ├── tables
│       └── tmp_wig
│           └── frag
│               ├── tmp
│               │   ├── NC_016838.1\012_forward.wig
│               │   ├── NC_016838.1\012_reverse.wig
│               │   ├── NC_016839.1\012_forward.wig
│               │   ├── NC_016839.1\012_reverse.wig
│               │   ├── NC_016840.1\012_forward.wig
│               │   ├── NC_016840.1\012_reverse.wig
│               │   ├── NC_016841.1\012_forward.wig
│               │   ├── NC_016841.1\012_reverse.wig
│               │   ├── NC_016845.1\012_forward.wig
│               │   ├── NC_016845.1\012_reverse.wig
│               │   ├── NC_016846.1\012_forward.wig
│               │   ├── NC_016846.1\012_reverse.wig
│               │   ├── NC_016847.1\012_forward.wig
│               │   └── NC_016847.1\012_reverse.wig
│               ├── WT_1.Forward.wig
│               ├── WT_1.Forward.wig_folder
│               │   ├── WT_1.Forward_STRAIN_NC_016838.1\012.wig
│               │   ├── WT_1.Forward_STRAIN_NC_016839.1\012.wig
│               │   ├── WT_1.Forward_STRAIN_NC_016840.1\012.wig
│               │   ├── WT_1.Forward_STRAIN_NC_016841.1\012.wig
│               │   ├── WT_1.Forward_STRAIN_NC_016845.1\012.wig
│               │   ├── WT_1.Forward_STRAIN_NC_016846.1\012.wig
│               │   └── WT_1.Forward_STRAIN_NC_016847.1\012.wig
│               ├── WT_1.Reverse.wig
│               ├── WT_1.Reverse.wig_folder
│               │   ├── WT_1.Reverse_STRAIN_NC_016838.1\012.wig
│               │   ├── WT_1.Reverse_STRAIN_NC_016839.1\012.wig
│               │   ├── WT_1.Reverse_STRAIN_NC_016840.1\012.wig
│               │   ├── WT_1.Reverse_STRAIN_NC_016841.1\012.wig
│               │   ├── WT_1.Reverse_STRAIN_NC_016845.1\012.wig
│               │   ├── WT_1.Reverse_STRAIN_NC_016846.1\012.wig
│               │   └── WT_1.Reverse_STRAIN_NC_016847.1\012.wig
│               ├── WT_2.Forward.wig
│               ├── WT_2.Forward.wig_folder
│               │   ├── WT_2.Forward_STRAIN_NC_016838.1\012.wig
│               │   ├── WT_2.Forward_STRAIN_NC_016839.1\012.wig
│               │   ├── WT_2.Forward_STRAIN_NC_016840.1\012.wig
│               │   ├── WT_2.Forward_STRAIN_NC_016841.1\012.wig
│               │   ├── WT_2.Forward_STRAIN_NC_016845.1\012.wig
│               │   ├── WT_2.Forward_STRAIN_NC_016846.1\012.wig
│               │   └── WT_2.Forward_STRAIN_NC_016847.1\012.wig
│               ├── WT_2.Reverse.wig
│               ├── WT_2.Reverse.wig_folder
│               │   ├── WT_2.Reverse_STRAIN_NC_016838.1\012.wig
│               │   ├── WT_2.Reverse_STRAIN_NC_016839.1\012.wig
│               │   ├── WT_2.Reverse_STRAIN_NC_016840.1\012.wig
│               │   ├── WT_2.Reverse_STRAIN_NC_016841.1\012.wig
│               │   ├── WT_2.Reverse_STRAIN_NC_016845.1\012.wig
│               │   ├── WT_2.Reverse_STRAIN_NC_016846.1\012.wig
│               │   └── WT_2.Reverse_STRAIN_NC_016847.1\012.wig
│               ├── WT_3.Forward.wig
│               ├── WT_3.Forward.wig_folder
│               │   ├── WT_3.Forward_STRAIN_NC_016838.1\012.wig
│               │   ├── WT_3.Forward_STRAIN_NC_016839.1\012.wig
│               │   ├── WT_3.Forward_STRAIN_NC_016840.1\012.wig
│               │   ├── WT_3.Forward_STRAIN_NC_016841.1\012.wig
│               │   ├── WT_3.Forward_STRAIN_NC_016845.1\012.wig
│               │   ├── WT_3.Forward_STRAIN_NC_016846.1\012.wig
│               │   └── WT_3.Forward_STRAIN_NC_016847.1\012.wig
│               ├── WT_3.Reverse.wig
│               └── WT_3.Reverse.wig_folder
│                   ├── WT_3.Reverse_STRAIN_NC_016838.1\012.wig
│                   ├── WT_3.Reverse_STRAIN_NC_016839.1\012.wig
│                   ├── WT_3.Reverse_STRAIN_NC_016840.1\012.wig
│                   ├── WT_3.Reverse_STRAIN_NC_016841.1\012.wig
│                   ├── WT_3.Reverse_STRAIN_NC_016845.1\012.wig
│                   ├── WT_3.Reverse_STRAIN_NC_016846.1\012.wig
│                   └── WT_3.Reverse_STRAIN_NC_016847.1\012.wig
└── used_annogesic_version.txt
```

It seemed that the directories were not identical with those in the "cat" commands. 

In addition, my wiggle files are as follows, having 7 chrom IDs, including 1 chromosome and 6 plasmids:
```
$ head /public/guanjiahao/rna_seq/ANNOgesic/input/wigs/fragment/WT_1.Forward.wig
track type=wiggle_0 name="WT_1"
variableStep chrom=NC_016845.1
130	3.00
131	3.00
132	3.00
133	3.00
134	3.00
135	3.00
136	3.00
137	7.00
...
variableStep chrom=NC_016839.1
...
variableStep chrom=NC_016840.1
...
variableStep chrom=NC_016847.1
...
variableStep chrom=NC_016841.1
...
variableStep chrom=NC_016838.1
...
variableStep chrom=NC_016846.1
```

I also have tried to install ANNOgesic from github and pip, respectively, but both reported the same errors. I am not sure what may caused the problem, it would be truly helpful if some possible solutions are provided.

best wishes,

Guan Jiahao

**Comment by Sung-Huan** [comment]
Hi,

I cannot see anything wrong from the command. If you feel ok, please send the wig files to me. I will take a look. Probably it is from the weird format of wig files or a bug in my code. If you do not want to put the files in the repo, you can send a mail to me directly. shyu@biochem.mpg.de

Best,
Sung-Huan

**Comment by gjh34** [comment]
Hi Sung-Huan,

Thank you very much for the prompt reply. The first 2 wig files I used have been sent to your email due to their large sizes. These wig files were generated from BAM files using bam2wig.py from RSeQC. 

Additionally, The first lines 'track type=wiggle_0 name="WT_1"' in these files were added according to this previous issue [https://github.com/Sung-Huan/ANNOgesic/issues/11](https://github.com/Sung-Huan/ANNOgesic/issues/11), as I have encountered the same problem.

Best wishes,
Guan Jiahao

**Comment by gjh34** [comment]
Hi Sung-Huan,


Thank you very much for the prompt reply. The first 2 wig files I used have been sent to your email due to their large sizes. These wig files were generated from BAM files using bam2wig.py from RSeQC.&nbsp;


Additionally, The first lines 'track type=wiggle_0 name="WT_1"' in these files were added according to this previous issue https://github.com/Sung-Huan/ANNOgesic/issues/11, as I have encountered the same problem.


Best wishes,
Guan Jiahao





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sung-Huan/ANNOgesic"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 下午5:51
收件人:&nbsp;"Sung-Huan/ANNOgesic"<ANNOgesic@noreply.github.com&gt;;
抄送:&nbsp;"浩浩荡荡"<303164609@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Sung-Huan/ANNOgesic] Transcript detection error (#22)





 
Hi,
 
I cannot see anything wrong from the command. If you feel ok, please send the wig files to me. I will take a look. Probably it is from the weird format of wig files or a bug in my code. If you do not want to put the files in the repo, you can send a mail to me directly. shyu@biochem.mpg.de
 
Best,
 Sung-Huan
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

WT_1.Forward.wig (55.70M, 2020年12月08日 18:19 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2461343420f1b2cea08d25264733041d5903060c04020e054c04070d551e0203025919565002051f05005505050102505102050461233665353e051a275c44450013501a165a51325c&code=aa44a362




WT_1.Reverse.wig (61.74M, 2020年12月08日 18:20 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=73356530ba1316c8f7d974221438001b550c0155045c54551b0251030b15065255544851530e071957035703575904055053010032283263626a541e605d44514446001e455155340b&code=65e02824

**Comment by Sung-Huan** [comment]
Ok, I figured it out. Your wig format is without span information. ANNOgesic is not able to handle it. Thus, I modified the code for managing the wig format without span information and update ANNOgesic to 1.0.19. Please update your version of ANNOgesic and it should be fine.

Btw, I suggest you to put genome annotations (gff file from RefSeq or some public database) as the input as well. It can improve the accuracy of the detection. And this file is also required for sRNA detection.

Best,
Sung-Huan

**Comment by gjh34** [comment]
Ah, thanks for your modification and suggestion. I have tried to update ANNOgesic to 1.0.19 and reruned the same command. However, the report messages were almost the same, with only the Traceback changed:
```
Running transcript detection
Parsing WT_1.Forward.wig
Parsing WT_1.Reverse.wig
Parsing WT_2.Forward.wig
Parsing WT_2.Reverse.wig
Parsing WT_3.Forward.wig
Parsing WT_3.Reverse.wig
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_1.Forward_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_1.Reverse_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_2.Forward_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_2.Reverse_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_3.Forward_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_3.Reverse_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_1.Forward_STRAIN_NC_016838.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_1.Reverse_STRAIN_NC_016838.1: No such file or directory
sh: line 1: .wig: command not found
...
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_3.Forward_STRAIN_NC_016841.1: No such file or directory
sh: line 1: .wig: command not found
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_3.Reverse_STRAIN_NC_016841.1: No such file or directory
sh: line 1: .wig: command not found
Importing fragment wig files
Computing transcripts for NC_016839.1

Computing transcripts for NC_016840.1

Computing transcripts for NC_016847.1

Computing transcripts for NC_016841.1

Computing transcripts for NC_016845.1

Computing transcripts for NC_016838.1

Computing transcripts for NC_016846.1

/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016839.1
_fragment
/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016840.1
_fragment
/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016847.1
_fragment
/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016841.1
_fragment
/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016845.1
_fragment
/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016838.1
_fragment
/public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/NC_016846.1
_fragment
Generating tables for the details
Traceback (most recent call last):
  File "/home/guanjiahao/miniconda3/bin/annogesic", line 2230, in <module>
    main()
  File "/home/guanjiahao/miniconda3/bin/annogesic", line 2146, in main
    args.func(controller)
  File "/home/guanjiahao/miniconda3/bin/annogesic", line 2183, in run_Transcript_Assembly
    controller.transcript()
  File "/home/guanjiahao/miniconda3/lib/python3.7/site-packages/annogesiclib/controller.py", line 463, in transcript
    transcript.run_transcript(args_tran, log)
  File "/home/guanjiahao/miniconda3/lib/python3.7/site-packages/annogesiclib/transcript.py", line 340, in run_transcript
    plot_tran(self.gff_outfolder, self.stat_path, args_tran.max_dist)
  File "/home/guanjiahao/miniconda3/lib/python3.7/site-packages/annogesiclib/plot_tran.py", line 36, in plot_tran
    plot(lens, os.path.join(stat_folder, prefix + "_length_all.png"))
  File "/home/guanjiahao/miniconda3/lib/python3.7/site-packages/annogesiclib/plot_tran.py", line 13, in plot
    ticks = max(lens) / 50
ValueError: max() arg is an empty sequence
```
The ANNOgesic project directory after running:
```
ANNOgesic
├── input
│   ├── BAMs
│   │   ├── BAMs_map_reference_genomes
│   │   │   ├── fragment
│   │   │   └── tex_notex
│   │   └── BAMs_map_related_genomes
│   │       ├── fragment
│   │       └── tex_notex
│   ├── databases
│   ├── manual_processing_sites
│   ├── manual_TSSs
│   ├── mutation_tables
│   ├── reads
│   ├── references
│   │   ├── annotations
│   │   └── fasta_files
│   ├── riboswitch_ID_file
│   ├── RNA_thermometer_ID_file
│   └── wigs
│       ├── fragment
│       │   ├── WT_1.Forward.wig
│       │   ├── WT_1.Reverse.wig
│       │   ├── WT_2.Forward.wig
│       │   ├── WT_2.Reverse.wig
│       │   ├── WT_3.Forward.wig
│       │   └── WT_3.Reverse.wig
│       └── tex_notex
├── output
│   └── transcripts
│       ├── gffs
│       │   ├── NC_016838.1\012_transcript.gff
│       │   ├── NC_016839.1\012_transcript.gff
│       │   ├── NC_016840.1\012_transcript.gff
│       │   ├── NC_016841.1\012_transcript.gff
│       │   ├── NC_016845.1\012_transcript.gff
│       │   ├── NC_016846.1\012_transcript.gff
│       │   └── NC_016847.1\012_transcript.gff
│       ├── log.txt
│       ├── statistics
│       ├── tables
│       │   ├── NC_016838.1\012_transcript.csv
│       │   ├── NC_016839.1\012_transcript.csv
│       │   ├── NC_016840.1\012_transcript.csv
│       │   ├── NC_016841.1\012_transcript.csv
│       │   ├── NC_016845.1\012_transcript.csv
│       │   ├── NC_016846.1\012_transcript.csv
│       │   └── NC_016847.1\012_transcript.csv
│       └── tmp_wig
│           └── frag
│               ├── tmp
│               │   ├── NC_016838.1\012_forward.wig
│               │   ├── NC_016838.1\012_reverse.wig
│               │   ├── NC_016839.1\012_forward.wig
│               │   ├── NC_016839.1\012_reverse.wig
│               │   ├── NC_016840.1\012_forward.wig
│               │   ├── NC_016840.1\012_reverse.wig
│               │   ├── NC_016841.1\012_forward.wig
│               │   ├── NC_016841.1\012_reverse.wig
│               │   ├── NC_016845.1\012_forward.wig
│               │   ├── NC_016845.1\012_reverse.wig
│               │   ├── NC_016846.1\012_forward.wig
│               │   ├── NC_016846.1\012_reverse.wig
│               │   ├── NC_016847.1\012_forward.wig
│               │   └── NC_016847.1\012_reverse.wig
│               ├── WT_1.Forward.wig
│               ├── WT_1.Forward.wig_folder
│               │   ├── WT_1.Forward_STRAIN_NC_016838.1\012.wig
│               │   ├── WT_1.Forward_STRAIN_NC_016839.1\012.wig
│               │   ├── WT_1.Forward_STRAIN_NC_016840.1\012.wig
│               │   ├── WT_1.Forward_STRAIN_NC_016841.1\012.wig
│               │   ├── WT_1.Forward_STRAIN_NC_016845.1\012.wig
│               │   ├── WT_1.Forward_STRAIN_NC_016846.1\012.wig
│               │   └── WT_1.Forward_STRAIN_NC_016847.1\012.wig
│               ├── WT_1.Reverse.wig
│               ├── WT_1.Reverse.wig_folder
│               │   ├── WT_1.Reverse_STRAIN_NC_016838.1\012.wig
│               │   ├── WT_1.Reverse_STRAIN_NC_016839.1\012.wig
│               │   ├── WT_1.Reverse_STRAIN_NC_016840.1\012.wig
│               │   ├── WT_1.Reverse_STRAIN_NC_016841.1\012.wig
│               │   ├── WT_1.Reverse_STRAIN_NC_016845.1\012.wig
│               │   ├── WT_1.Reverse_STRAIN_NC_016846.1\012.wig
│               │   └── WT_1.Reverse_STRAIN_NC_016847.1\012.wig
│               ├── WT_2.Forward.wig
│               ├── WT_2.Forward.wig_folder
│               │   ├── WT_2.Forward_STRAIN_NC_016838.1\012.wig
│               │   ├── WT_2.Forward_STRAIN_NC_016839.1\012.wig
│               │   ├── WT_2.Forward_STRAIN_NC_016840.1\012.wig
│               │   ├── WT_2.Forward_STRAIN_NC_016841.1\012.wig
│               │   ├── WT_2.Forward_STRAIN_NC_016845.1\012.wig
│               │   ├── WT_2.Forward_STRAIN_NC_016846.1\012.wig
│               │   └── WT_2.Forward_STRAIN_NC_016847.1\012.wig
│               ├── WT_2.Reverse.wig
│               ├── WT_2.Reverse.wig_folder
│               │   ├── WT_2.Reverse_STRAIN_NC_016838.1\012.wig
│               │   ├── WT_2.Reverse_STRAIN_NC_016839.1\012.wig
│               │   ├── WT_2.Reverse_STRAIN_NC_016840.1\012.wig
│               │   ├── WT_2.Reverse_STRAIN_NC_016841.1\012.wig
│               │   ├── WT_2.Reverse_STRAIN_NC_016845.1\012.wig
│               │   ├── WT_2.Reverse_STRAIN_NC_016846.1\012.wig
│               │   └── WT_2.Reverse_STRAIN_NC_016847.1\012.wig
│               ├── WT_3.Forward.wig
│               ├── WT_3.Forward.wig_folder
│               │   ├── WT_3.Forward_STRAIN_NC_016838.1\012.wig
│               │   ├── WT_3.Forward_STRAIN_NC_016839.1\012.wig
│               │   ├── WT_3.Forward_STRAIN_NC_016840.1\012.wig
│               │   ├── WT_3.Forward_STRAIN_NC_016841.1\012.wig
│               │   ├── WT_3.Forward_STRAIN_NC_016845.1\012.wig
│               │   ├── WT_3.Forward_STRAIN_NC_016846.1\012.wig
│               │   └── WT_3.Forward_STRAIN_NC_016847.1\012.wig
│               ├── WT_3.Reverse.wig
│               └── WT_3.Reverse.wig_folder
│                   ├── WT_3.Reverse_STRAIN_NC_016838.1\012.wig
│                   ├── WT_3.Reverse_STRAIN_NC_016839.1\012.wig
│                   ├── WT_3.Reverse_STRAIN_NC_016840.1\012.wig
│                   ├── WT_3.Reverse_STRAIN_NC_016841.1\012.wig
│                   ├── WT_3.Reverse_STRAIN_NC_016845.1\012.wig
│                   ├── WT_3.Reverse_STRAIN_NC_016846.1\012.wig
│                   └── WT_3.Reverse_STRAIN_NC_016847.1\012.wig
└── used_annogesic_version.txt
```
After inspection for the ANNOgesic project directory and the error message, I found two possible problems:
(1) The file `WT_1.Forward_STRAIN_NC_016838.1\012.wig` is in the `ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_1.Forward.wig_folder` directory, which is different from the directory in the `cat` command. And the file in the `ANNOgesic/output/transcripts/tmp_wig/frag/tmp` is `NC_016838.1\012_forward.wig`
(2) It seems that sh separated the filename `WT_1.Forward_STRAIN_NC_016845.1\012.wig` into two lines divided by '\012' that equal to '\n', which resulted in the following mseeage: 
```
cat: /public/guanjiahao/rna_seq/ANNOgesic/output/transcripts/tmp_wig/frag/tmp/WT_1.Forward_STRAIN_NC_016845.1: No such file or directory
sh: line 1: .wig: command not found
```
I am not sure if it was the problem caused by the tmp directory or the name of tmp files, but it is possible according to the report messages.

Best wishes,
Guan Jiahao

**Comment by gjh34** [comment]
Hi Sung-Huan,

I finally tried to add "span=1" after "chrom=XXX" in wig files, and reruned the same command, which worked well. So the problem was really the lack of the span information in my wig files. Nonetheless, I still do not know what may cause the aforementioned problem. Maybe the '\n' at the end of this line `variableStep chrom=NC_016839.1` was also written into the tmp filename, which would lead to the above problem.

Anyway, thanks for your efforts to solve my issue and your sincere suggestions. ANNOgesic is also a nice and useful tool.

Best wishes,
Guan Jiahao

**Comment by Sung-Huan** [comment]
Hi,

I am so sorry, I miss uploading a script. I already uploaded it and make a new release. And you are right, the issue it the /n.

Best,
Sung-Huan

**Comment by gjh34** [comment]
Hi,

Thanks for your efforts to solve this issue. Now ANNOgesic worked pretty well. Btw, ANNOgesic is really a nice tool.

Best,
Guan Jiahao
