### ISSUE TITLE
optimize_tss_ps error:TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by Blehri** [Sung-Huan/ANNOgesic#28]
Hi,

I am trying to run optimize_tss_ps by using:

```
singularity` exec -B /home/ubuntu/anaconda3/bin/annogesic annogesic.img \
annogesic optimize_tss_ps \
    --fasta_files /home/ubuntu/annogesic_2/input/references/fasta_files/NC_009839.fa \
    --annotation_files /home/ubuntu/annogesic_2/input/references/annotations/NC_009839.gff \
    --tex_notex_libs $TEX_LIBS \
    --condition_names TSS --steps 25 \
    --manual_files /home/ubuntu/annogesic_2/input/manual_TSSs/NC_009839_manual_TSS.gff \
    --curated_sequence_length NC_009839:200000 \
    --replicate_tex all_1 \
    --project_path /home/ubuntu/annogesic_2
```

with $TEX_LIBS being

```
TEX_LIBS="$WIG_FOLDER/GSM951380_Log_81116_R1_minus_TEX_in_NC_009839_minus.wig:notex:1:a:- \
$WIG_FOLDER/GSM951380_Log_81116_R1_minus_TEX_in_NC_009839_plus.wig:notex:1:a:+ \
$WIG_FOLDER/GSM951381_Log_81116_R1_plus_TEX_in_NC_009839_minus.wig:tex:1:a:- \
$WIG_FOLDER/GSM951381_Log_81116_R1_plus_TEX_in_NC_009839_plus.wig:tex:1:a:+ \
$WIG_FOLDER/GSM951382_Log_81116_R2_minus_TEX_in_NC_009839_minus.wig:notex:1:b:- \
$WIG_FOLDER/GSM951382_Log_81116_R2_minus_TEX_in_NC_009839_plus.wig:notex:1:b:+ \
$WIG_FOLDER/GSM951383_Log_81116_R2_plus_TEX_in_NC_009839_minus.wig:tex:1:b:- \
$WIG_FOLDER/GSM951383_Log_81116_R2_plus_TEX_in_NC_009839_plus.wig:tex:1:b:+"
```

I get the error
```
Running optimization of TSS prediction
Parsing GSM951381_Log_81116_R1_plus_TEX_in_NC_009839_plus.wig
Parsing GSM951383_Log_81116_R2_plus_TEX_in_NC_009839_minus.wig
Parsing GSM951381_Log_81116_R1_plus_TEX_in_NC_009839_minus.wig
Parsing GSM951380_Log_81116_R1_minus_TEX_in_NC_009839_minus.wig
Parsing GSM951383_Log_81116_R2_plus_TEX_in_NC_009839_plus.wig
Parsing GSM951382_Log_81116_R2_minus_TEX_in_NC_009839_minus.wig
Parsing GSM951380_Log_81116_R1_minus_TEX_in_NC_009839_plus.wig
Parsing GSM951382_Log_81116_R2_minus_TEX_in_NC_009839_plus.wig
Parsing NC_009839.gff
Parsing NC_009839.fa
Parsing NC_009839_manual_TSS.gff
Traceback (most recent call last):
  File "/usr/local/bin/annogesic", line 2238, in <module>
    main()
  File "/usr/local/bin/annogesic", line 2154, in main
    args.func(controller)
  File "/usr/local/bin/annogesic", line 2182, in optimize_TSSpredator
    controller.optimize()
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/controller.py", line 379, in optimize
    optimize_tss(args_ops, log)
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/optimize.py", line 31, in optimize_tss
    Multiparser().parser_gff(args_ops.manuals, None)
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/multiparser.py", line 283, in parser_gff
    os.path.join(gff_folder, "tmp.gff"))
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/helper.py", line 219, in sort_gff
    for entry in self.gff3parser.entries(g_f):
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/gff3.py", line 26, in entries
    yield self._dict_to_entry(entry_dict)
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/gff3.py", line 29, in _dict_to_entry
    return Gff3Entry(entry_dict)
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/gff3.py", line 56, in __init__
    start, end = sorted([int(entry_dict["start"]), int(entry_dict["end"])])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

please also find the wiggle files and fasta file attached i obtained the files from geo with accession number GSE38883.
[GSM951380_Log_81116_R1_minus_TEX_in_NC_009839_plus.wig.txt](https://github.com/Sung-Huan/ANNOgesic/files/7817806/GSM951380_Log_81116_R1_minus_TEX_in_NC_009839_plus.wig.txt)
[NC_009839.fa.txt](https://github.com/Sung-Huan/ANNOgesic/files/7817804/NC_009839.fa.txt)
[GSM951380_Log_81116_R1_minus_TEX_in_NC_009839_minus.wig.txt](https://github.com/Sung-Huan/ANNOgesic/files/7817805/GSM951380_Log_81116_R1_minus_TEX_in_NC_009839_minus.wig.txt)

**Comment by Sung-Huan** [comment]
Hi,

It looks like your NC_009839_manual_TSS.gff has format issue. Could you also provide your NC_009839_manual_TSS.gff?

Best,
Sung-Huan

**Comment by Blehri** [comment]
Hi, 

thanks please find the manual_TSS.gff file attached
[NC_009839_manual_TSS.gff.txt](https://github.com/Sung-Huan/ANNOgesic/files/7820918/NC_009839_manual_TSS.gff.txt)

**Comment by Sung-Huan** [comment]
Hi,

Your TSS gff file is definitely not correct. I guess you download it directly from my git repo. Perhaps, you download it via html based format. You can open your manual_TSS.gff by any kinds of editors, then you will find out the error.

Best,
Sung-Huan

**Comment by Blehri** [comment]
ahh yea, thanks it worked

**Comment by Sung-Huan** [comment]
Hi,

I guess this error is from NC_002163.1_TSS.gff. This gff file contains a empty line in the end of the file. Please remove that line and run transcript detection again. If you still get the error, I can try to run it from my side.

Best,
Sung-Huan
