### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by sternp** [Sung-Huan/ANNOgesic#31]
Hi, 

I'm getting the following error when I try to run the docker image on a computing cluster I have have root access to:

```
sternesp@cl5n008:~/lustre-microbiome/users/sternesp/annogesic$ singularity exec -B /lustre/work-lustre/microbiome/users/sternesp/annogesic/ANNOgesic annogesic.img \
> annogesic \
> transcript \
> --annotation_files /home/sternesp/lustre-microbiome/users/sternesp/annogesic/ANNOgesic/input/references/annotations/GUT_GENOME000001.gff \
> --project_path /lustre/work-lustre/microbiome/users/sternesp/annogesic/ANNOgesic \
> --frag_lib /lustre/work-lustre/microbiome/users/sternesp/annogesic/ANNOgesic/input/wigs/fragment/rev2.wig:frag:1:a:- \
> /lustre/work-lustre/microbiome/users/sternesp/annogesic/ANNOgesic/input/wigs/fragment/fwd2.wig:frag:1:a:+ \
> --replicate_frag all_1

       ___    _   ___   ______                  _     
      /   |  / | / / | / / __ \____ ____  _____(_)____ \
  __ / /| | /  |/ /  |/ / / / / __ `/ _ \/ ___/ / ___/__\
 |  / ___ |/ /|  / /|  / /_/ / /_/ /  __(__  ) / /__    /
 | /_/  |_/_/ |_/_/ |_/\____/\__, /\___/____/_/\___/   /
 |                          /____/ 
 |__________________
 |_____________________
 |________________________________________________
 |                                                \
 |________________________________________________/

Running transcript detection
Parsing GUT_GENOME000001.gff
Parsing rev2.wig
Parsing fwd2.wig
Merging wig files of GUT_GENOME000001
Importing fragment wig files
Computing transcripts for GUT_GENOME000001
Traceback (most recent call last):
  File "/usr/local/bin/annogesic", line 2238, in <module>
    main()
  File "/usr/local/bin/annogesic", line 2154, in main
    args.func(controller)
  File "/usr/local/bin/annogesic", line 2191, in run_Transcript_Assembly
    controller.transcript()
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/controller.py", line 464, in transcript
    transcript.run_transcript(args_tran, log)
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/transcript.py", line 314, in run_transcript
    self.tmps["gff"])
  File "/usr/local/lib/python3.6/dist-packages/annogesiclib/helper.py", line 224, in sort_gff
    out = open(out_file, "w")
OSError: [Errno 30] Read-only file system: 'tmp.gff'

```

**Comment by Sung-Huan** [comment]
Hi,

I guess you run ANNOgesic under the root folder directly (you did not change the folder when you enter into docker container). At root folder, the file is not allowed to be written for the concern of safety. So that, ANNOgesic cannot generate some intermediate files. What you need to do is creating a new folder and run ANNOgesic there.

Best,
Sung-Huan
